.PHONY: install
install:
	cp .vimrc ~/
	cp -r .vim ~/
	go get -u github.com/mdempsky/gocode
	#git clone https://github.com/AndrewRadev/splitjoin.vim.git ~/.vim/plugged/splitjoin
	#git clone https://github.com/fatih/vim-go.git ~/.vim/plugged/splitjoin
